const sampleListings = [
  {
    title: "Cozy Beachfront Cottage",
    description: "Escape to this charming beachfront cottage for a relaxing getaway. Enjoy stunning ocean views.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1552733407-5d5c46c3bb3b?auto=format&fit=crop&w=800&q=60" },
    price: 1500,
    location: "Malibu",
    country: "United States",
  },
  {
    title: "Modern Loft in Downtown",
    description: "Stay in the heart of the city in this stylish loft apartment. Perfect for urban explorers!",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=800&q=60" },
    price: 1200,
    location: "New York City",
    country: "United States",
  },
  {
    title: "Mountain Retreat",
    description: "Unplug and unwind in this peaceful mountain cabin. Surrounded by nature.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=800&q=60" },
    price: 1000,
    location: "Aspen",
    country: "United States",
  },
  {
    title: "Historic Villa in Tuscany",
    description: "Experience the charm of Tuscany in this beautifully restored villa. Explore the rolling hills.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=60" },
    price: 2500,
    location: "Florence",
    country: "Italy",
  },
  {
    title: "Secluded Treehouse Getaway",
    description: "Live among the treetops in this unique treehouse retreat. A true nature lover's paradise.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=800&q=60" },
    price: 800,
    location: "Portland",
    country: "United States",
  },
  {
    title: "Beachfront Bliss in Bali",
    description: "Relax on the white sands of Bali in this luxury beachfront villa with a private pool.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=800&q=60" },
    price: 3000,
    location: "Bali",
    country: "Indonesia",
  },
  {
    title: "Ski Chalet in Aspen",
    description: "Hit the slopes in style with this cozy ski-in/ski-out chalet in the heart of Aspen.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?auto=format&fit=crop&w=800&q=60" },
    price: 4000,
    location: "Aspen",
    country: "United States",
  },
  {
    title: "Iconic Skyline Apartment",
    description: "Enjoy breathtaking views of the city skyline from this ultra-modern penthouse.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1493397212122-2b85edf36960?auto=format&fit=crop&w=800&q=60" },
    price: 5500,
    location: "Dubai",
    country: "UAE",
  },
  {
    title: "Safari Tent in Serengeti",
    description: "Experience the magic of the African savanna in this luxury safari tent.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1493246507139-91e8bef99c1e?auto=format&fit=crop&w=800&q=60" },
    price: 1800,
    location: "Serengeti",
    country: "Tanzania",
  },
  {
    title: "Historic Canal House",
    description: "Stay in a beautifully preserved canal house in the heart of Amsterdam's historic district.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=60" },
    price: 2200,
    location: "Amsterdam",
    country: "Netherlands",
  },
  {
    title: "Private Island in Maldives",
    description: "Escape to your own private island paradise in the turquoise waters of the Maldives.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1514282401047-d79a71a590e8?auto=format&fit=crop&w=800&q=60" },
    price: 10000,
    location: "Maldives",
    country: "Maldives",
  },
  {
    title: "Luxury Cabin in Swiss Alps",
    description: "Experience the ultimate mountain getaway in this stunning luxury cabin.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1502784444187-359ac186c5bb?auto=format&fit=crop&w=800&q=60" },
    price: 3500,
    location: "Zermatt",
    country: "Switzerland",
  },
  {
    title: "Desert Oasis in Morocco",
    description: "Stay in a traditional riad with a lush courtyard garden and cooling fountain.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=800&q=60" },
    price: 1400,
    location: "Marrakech",
    country: "Morocco",
  },
  {
    title: "Tropical Villa in Phuket",
    description: "Surround yourself with palm trees and tropical flowers in this spacious villa.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1533750350321-d3f82220fc5d?auto=format&fit=crop&w=800&q=60" },
    price: 2100,
    location: "Phuket",
    country: "Thailand",
  },
  {
    title: "Luxury Yacht in Monaco",
    description: "Live like a celebrity on this sleek luxury yacht anchored in the harbor of Monaco.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1567620905732-2d1ec7bb7445?auto=format&fit=crop&w=800&q=60" },
    price: 15000,
    location: "Monaco",
    country: "Monaco",
  },
  {
    title: "Rustic Farmhouse in Provence",
    description: "Enjoy the simple pleasures of country life in this charming stone farmhouse.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=800&q=60" },
    price: 1100,
    location: "Provence",
    country: "France",
  },
  {
    title: "Contemporary Villa in Ibiza",
    description: "Host the ultimate party in this sleek contemporary villa with a sprawling terrace.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1512918766674-63c6835a6439?auto=format&fit=crop&w=800&q=60" },
    price: 6000,
    location: "Ibiza",
    country: "Spain",
  },
  {
    title: "Eco-Friendly Lodge in Costa Rica",
    description: "Immerse yourself in nature at this sustainable eco-lodge in the heart of the rainforest.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1518732714860-b62714ce0c59?auto=format&fit=crop&w=800&q=60" },
    price: 1300,
    location: "Tortuguero",
    country: "Costa Rica",
  },
  {
    title: "Oceanview Apartment in Sydney",
    description: "Wake up to the sound of the waves in this bright and airy oceanview apartment.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?auto=format&fit=crop&w=800&q=60" },
    price: 2400,
    location: "Sydney",
    country: "Australia",
  },
  {
    title: "Lakeside Cottage in Canada",
    description: "Spend your days fishing and canoeing on the peaceful lake at this cozy cottage.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?auto=format&fit=crop&w=800&q=60" },
    price: 900,
    location: "Ontario",
    country: "Canada",
  },
  {
    title: "Grand Castle in Scotland",
    description: "Feel like royalty staying in a real 14th-century castle in the Highlands.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1533154683836-84ea7a0bc310?auto=format&fit=crop&w=800&q=60" },
    price: 8000,
    location: "Highlands",
    country: "United Kingdom",
  },
  {
    title: "Zen Boutique Hotel",
    description: "Find your inner peace in this minimalist Japanese-inspired boutique hotel.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=800&q=60" },
    price: 1900,
    location: "Kyoto",
    country: "Japan",
  },
  {
    title: "Cliffside Estate in Santorini",
    description: "Breathtaking views of the Aegean Sea from your private caldera-front villa.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&w=800&q=60" },
    price: 4500,
    location: "Oia",
    country: "Greece",
  },
  {
    title: "Urban Jungle Apartment",
    description: "A lush, plant-filled oasis in the middle of Berlin's coolest neighborhood.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1449156059344-be398b2b2d28?auto=format&fit=crop&w=800&q=60" },
    price: 1100,
    location: "Berlin",
    country: "Germany",
  },
  {
    title: "Snowy Igloo Experience",
    description: "Sleep under the Northern Lights in a custom-built luxury snow igloo.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1483921020237-2ff51e8e4b22?auto=format&fit=crop&w=800&q=60" },
    price: 3200,
    location: "Lapland",
    country: "Finland",
  },
  {
    title: "Goan Heritage Villa",
    description: "Traditional Portuguese-style villa with modern luxury near the beach.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=800&q=60" },
    price: 2500,
    location: "Goa",
    country: "India",
  },
  {
    title: "Floating Houseboat",
    description: "Live on the backwaters in a luxury houseboat with a personal chef.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1593642532400-2682810df593?auto=format&fit=crop&w=800&q=60" },
    price: 1800,
    location: "Alleppey",
    country: "India",
  },
  {
    title: "Royal Palace Suite",
    description: "Stay in a genuine palace and experience the lifestyle of Indian royalty.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1598977123418-45003330062f?auto=format&fit=crop&w=800&q=60" },
    price: 7000,
    location: "Jaipur",
    country: "India",
  },
  {
    title: "Jungle Safari Lodge",
    description: "Located at the edge of the tiger reserve, perfect for wildlife enthusiasts.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1540541338287-41700207dee6?auto=format&fit=crop&w=800&q=60" },
    price: 2200,
    location: "Ranthambore",
    country: "India",
  },
  {
    title: "Mountain Tea Plantation",
    description: "Wake up to misty mornings in a colonial bungalow surrounded by tea gardens.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1527668752968-14dc70a27c95?auto=format&fit=crop&w=800&q=60" },
    price: 1500,
    location: "Munnar",
    country: "India",
  },
  {
    title: "Parisian Chic Studio",
    description: "A bright studio with a view of the Eiffel Tower from your balcony.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=800&q=60" },
    price: 2800,
    location: "Paris",
    country: "France",
  },
  {
    title: "Overwater Bungalow",
    description: "Luxury villas sitting right over the crystal clear lagoon waters.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=800&q=60" },
    price: 9000,
    location: "Bora Bora",
    country: "French Polynesia",
  },
  {
    title: "Vintage Airstream in Desert",
    description: "Glamping at its finest in a retro trailer under the desert stars.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1523987355523-c7b5b0dd90a7?auto=format&fit=crop&w=800&q=60" },
    price: 600,
    location: "Joshua Tree",
    country: "United States",
  },
  {
    title: "Hidden Cave Hotel",
    description: "Stay in a suite carved into the ancient rock formations of Cappadocia.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1505567745926-ba89000d255a?auto=format&fit=crop&w=800&q=60" },
    price: 1700,
    location: "Cappadocia",
    country: "Turkey",
  },
  {
    title: "Modern Glass House",
    description: "Surrounded by forest, this glass house offers 360-degree nature views.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1518780664697-55e3ad937233?auto=format&fit=crop&w=800&q=60" },
    price: 3500,
    location: "Oslo",
    country: "Norway",
  },
  {
    title: "Mediterranean Stone Villa",
    description: "A stunning villa with blue shutters and a private olive grove.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=60" },
    price: 3100,
    location: "Mykonos",
    country: "Greece",
  },
  {
    title: "Cozy Lakefront Cabin",
    description: "Wooden cabin with a private dock, perfect for morning coffee by the lake.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&w=800&q=60" },
    price: 1200,
    location: "Lake Tahoe",
    country: "United States",
  },
  {
    title: "Boutique Riad in Fes",
    description: "Exquisite tile work and a tranquil fountain in this historic Moroccan home.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1549918830-11ec3d405f19?auto=format&fit=crop&w=800&q=60" },
    price: 1350,
    location: "Fes",
    country: "Morocco",
  },
  {
    title: "Minimalist Beach House",
    description: "Clean lines and ocean breezes in this architecturally designed home.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?auto=format&fit=crop&w=800&q=60" },
    price: 2700,
    location: "Tulum",
    country: "Mexico",
  },
  {
    title: "Skyscraper Suite",
    description: "Floor-to-ceiling windows overlooking the neon lights of Shinjuku.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=800&q=60" },
    price: 4200,
    location: "Tokyo",
    country: "Japan",
  },
  {
    title: "Countryside Manor",
    description: "An elegant English manor with manicured gardens and high tea service.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1513584684374-8bdb7489feef?auto=format&fit=crop&w=800&q=60" },
    price: 3800,
    location: "Cotswolds",
    country: "United Kingdom",
  },
  {
    title: "Riverside Bamboo Hut",
    description: "Eco-friendly living in a stunning bamboo structure by the river.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1537944434965-cf4679d1a598?auto=format&fit=crop&w=800&q=60" },
    price: 750,
    location: "Ubud",
    country: "Indonesia",
  },
  {
    title: "Penthouse with Infinity Pool",
    description: "Swim above the city in your private rooftop infinity pool.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=800&q=60" },
    price: 6500,
    location: "Singapore",
    country: "Singapore",
  },
  {
    title: "Secluded Arctic Lodge",
    description: "Watch the snow fall from the comfort of a warm, modern lodge.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1483921020237-2ff51e8e4b22?auto=format&fit=crop&w=800&q=60" },
    price: 2900,
    location: "Reykjavik",
    country: "Iceland",
  },
  {
    title: "Luxury Vineyard Estate",
    description: "Stay in the heart of wine country with private tastings included.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1505916055359-dec031484432?auto=format&fit=crop&w=800&q=60" },
    price: 3400,
    location: "Napa Valley",
    country: "United States",
  },
  {
    title: "Spanish Colonial Home",
    description: "Bright colors and a central courtyard in this beautiful historic home.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1560185007-cde436f6a4d0?auto=format&fit=crop&w=800&q=60" },
    price: 1600,
    location: "Cartagena",
    country: "Colombia",
  },
  {
    title: "Modern Mountain Villa",
    description: "Sleek architecture meets rugged peaks in this stunning vacation home.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1542718610-a1d656d1884c?auto=format&fit=crop&w=800&q=60" },
    price: 2300,
    location: "Queenstown",
    country: "New Zealand",
  },
  {
    title: "Historic Townhouse",
    description: "Elegant brownstone living in a quiet, tree-lined neighborhood.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1449844908441-8829872d2607?auto=format&fit=crop&w=800&q=60" },
    price: 2100,
    location: "Boston",
    country: "United States",
  },
  {
    title: "Sun-Drenched Island Loft",
    description: "Wake up to ocean views and bright Mediterranean sunlight.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1515238152791-8216bfdf89a7?auto=format&fit=crop&w=800&q=60" },
    price: 1850,
    location: "Hvar",
    country: "Croatia",
  },
  {
    title: "Tropical Rainforest Treehouse",
    description: "An immersive experience high in the canopy with modern amenities.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=60" },
    price: 1150,
    location: "Arenal",
    country: "Costa Rica",
  }
];

module.exports = { data: sampleListings };
